# Generated by Django 4.2.1 on 2023-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusStudenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusStudenta', models.CharField(choices=[('None', 'NONE'), ('Izvanredni', 'IZVANREDNI'), ('Redovni', 'REDOVNI')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Prijavljen', 'PRI'), ('Položen', 'POL'), ('Izgubljen potpis', 'PAD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='uloge',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Profesor', 'PROF'), ('Student', 'STUDENT')], max_length=20),
        ),
    ]
